import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="/pokedex"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>Go to Pokedex Page</h2>
            <p>Click here to got to&nbsp; Pokedex page.</p>
          </a>

          <a
            href="/randomPokemon"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Random Pokemon<span>-&gt;</span>
            </h2>
            <p>Click here to go get a random&nbsp;Pokemon!</p>
          </a>
        </div>
      </main>
    </>
  );
}
